# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f7a7c2d968f3636f87140b475aab067888ed47f9ce708ce035aa577b297e524f281157e1cfac8065937b9f3812125f6740635d0781871d785cfb7973d1007f7

test:
  secret_key_base: 8ed8a729f3725ea7f7f7eac09d2a67e9fed00c5fa80fa28d914ec9ba794a16f9908c216d1ee83c530ce707714789658dc7c31214f5a321ddbe5e5bbc83acfbf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
